Repository WhosInRoom/WhosInClient, pull requests merged in 2025-09, with the labels that each got.

#5 [FIX]: navigation-compose 버전 다운그레이드를 통해 iOS 빌드 문제 해결
  gradle/libs.versions.toml
Labels: FIX

#10 [CHORE] Ktor, Koin 세팅
  composeApp/build.gradle.kts
  composeApp/src/androidMain/AndroidManifest.xml
  composeApp/src/androidMain/kotlin/org/whosin/client/WhosInApplication.kt
  composeApp/src/androidMain/kotlin/org/whosin/client/di/DIModules.android.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/App.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/core/network/.gitkeep
  composeApp/src/commonMain/kotlin/org/whosin/client/core/network/ApiResult.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/core/network/HttpClientFactory.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/dto/.gitkeep
  composeApp/src/commonMain/kotlin/org/whosin/client/data/dto/request/LoginRequestDto.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/dto/response/DummyJokeResponseDto.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/dto/response/LoginResponseDto.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/remote/DummyDataSource.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/remote/RemoteClubDataSource.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/remote/RemoteMemberDataSource.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/repository/.gitkeep
  composeApp/src/commonMain/kotlin/org/whosin/client/data/repository/ClubRepository.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/repository/DummyRepository.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/repository/MemberRepository.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/di/.gitkeep
  composeApp/src/commonMain/kotlin/org/whosin/client/di/DIModules.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/di/initKoin.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/LoginViewModel.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/dummy/DummyScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/dummy/DummyViewModel.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/home/HomeViewModel.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/mypage/MyPageViewModel.kt
  composeApp/src/iosMain/kotlin/org/whosin/client/MainViewController.kt
  composeApp/src/iosMain/kotlin/org/whosin/client/di/DIModules.ios.kt
  composeApp/src/jvmMain/kotlin/org/whosin/client/di/DIModules.jvm.kt
  composeApp/src/jvmMain/kotlin/org/whosin/client/main.kt
  composeApp/src/wasmJsMain/kotlin/org/whosin/client/di/DIModules.wasmJs.kt
  composeApp/src/wasmJsMain/kotlin/org/whosin/client/main.kt
  gradle/libs.versions.toml
Labels: CHORE, REFACTOR, OK Merge

#14 [CI] ci.yml 파일 생성
  .github/workflows/ci.yml
Labels: CI

#15 [CHORE] buildkonfig 플러그인 추가, base url 설정
  .github/workflows/ci.yml
  build.gradle.kts
  composeApp/build.gradle.kts
  composeApp/src/commonMain/kotlin/org/whosin/client/core/network/HttpClientFactory.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/remote/DummyDataSource.kt
  gradle/libs.versions.toml
Labels: CHORE

#16 [UI] 로그인 화면 ui 구현
  composeApp/build.gradle.kts
  composeApp/src/commonMain/composeResources/drawable/ic_back.png
  composeApp/src/commonMain/composeResources/drawable/img_logo_orange.png
  composeApp/src/commonMain/composeResources/drawable/img_logo_white.png
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/org/whosin/client/App.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/core/navigation/Route.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/core/navigation/WhosInNavGraph.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/di/DIModules.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/LoginScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/clubcode/ClubCodeInputScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/clubcode/ClubCodeState.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/EmailVerificationScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/FindPasswordScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/LoginScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/NicknameInputScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/PasswordInputScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/SignupEmailInputScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/SplashScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/component/CommonLoginButton.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/component/CommonLoginInputField.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/component/NumberInputBox.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/auth/login/viewmodel/LoginViewModel.kt
Labels: FEAT, UI, OK Merge

#21 [CHORE,FEAT] 플랫폼별 TokenManager 구현, Ktor client에서의 토큰 처리 구현
  composeApp/build.gradle.kts
  composeApp/src/androidMain/kotlin/org/whosin/client/datastore/createDataStore.android.kt
  composeApp/src/androidMain/kotlin/org/whosin/client/di/DIModules.android.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/App.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/core/datastore/TokenManager.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/core/datastore/TokenManagerImpl.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/core/datastore/createDataStore.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/core/network/HttpClientFactory.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/data/dto/request/ReissueTokenRequestDto.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/di/DIModules.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/dummy/TokenTestScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/dummy/TokenTestViewModel.kt
  composeApp/src/iosMain/kotlin/org/whosin/client/datastore/createDataStore.ios.kt
  composeApp/src/iosMain/kotlin/org/whosin/client/di/DIModules.ios.kt
  composeApp/src/jvmMain/kotlin/org/whosin/client/datastore/createDataStore.jvm.kt
  composeApp/src/jvmMain/kotlin/org/whosin/client/di/DIModules.jvm.kt
  composeApp/src/wasmJsMain/kotlin/org/whosin/client/datastore/JsTokenManagerImpl.kt
  composeApp/src/wasmJsMain/kotlin/org/whosin/client/di/DIModules.wasmJs.kt
  gradle/libs.versions.toml
Labels: FEAT, CHORE, OK Merge

#23 [UI] 동아리 목록 컴포넌트 구현
  composeApp/src/commonMain/composeResources/files/ic_x.svg
  composeApp/src/commonMain/kotlin/org/whosin/client/data/dto/response/MyClubResponseDto.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/mypage/MyPageScreen.kt
  composeApp/src/commonMain/kotlin/org/whosin/client/presentation/mypage/component/MyClubComponent.kt
Labels: REFACTOR, UI, OK Merge
